triggers:
- envs: []
  last_enabled_at: 2024-02-09 05:11:18.337919
  name: timed-run-5-am
  pipeline_uuid: green_taxi_etl
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    skip_if_previous_running: true
    timeout: '600'
    timeout_status: failed
  sla: null
  start_time: 2024-02-08 11:00:00
  status: active
  variables: {}
